project_id = "nalbieiwczhmbmschmao"

[functions.submit-consultation]
verify_jwt = false

[functions.send-consultation-email]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.create-payment]
verify_jwt = true

[functions.create-stripe-checkout]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

# Dwolla functions
[functions.dwolla-create-customer]
verify_jwt = true

[functions.dwolla-create-and-verify-funding-source]
verify_jwt = true

[functions.dwolla-transfer]
verify_jwt = true
