project_id = "nalbieiwczhmbmschmao"

[functions.submit-consultation]
verify_jwt = false

[functions.send-consultation-email]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.create-payment]
verify_jwt = true

# Stripe payment processing
[functions.create-stripe-checkout]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true